/* Automatically generated by './build/bin/build-entry.js' */

import Dialog from '../packages/dialog/index.js';
import Autocomplete from '../packages/autocomplete/index.js';
import Dropdown from '../packages/dropdown/index.js';
import DropdownMenu from '../packages/dropdown-menu/index.js';
import DropdownItem from '../packages/dropdown-item/index.js';
import Select from '../packages/select/index.js';
import Option from '../packages/option/index.js';
import OptionGroup from '../packages/option-group/index.js';
import Button from '../packages/button/index.js';
import ButtonGroup from '../packages/button-group/index.js';
import Tooltip from '../packages/tooltip/index.js';
import Tabs from '../packages/tabs/index.js';
import TabPane from '../packages/tab-pane/index.js';
import Row from '../packages/row/index.js';
import Col from '../packages/col/index.js';
import Loading from '../packages/loading/index.js';
import Tag from '../packages/tag/index.js';
import Icon from '../packages/icon/index.js';
import Spinner from '../packages/spinner/index.js';
import Message from '../packages/message/index.js';
import Badge from '../packages/badge/index.js';
import Card from '../packages/card/index.js';
import Scrollbar from '../packages/scrollbar/index.js';
import Collapse from '../packages/collapse/index.js';
import CollapseItem from '../packages/collapse-item/index.js';
import Link from '../packages/link/index.js';
import Divider from '../packages/divider/index.js';
import Backtop from '../packages/backtop/index.js';
import Popover from '../packages/popover/index.js';
import locale from 'element-ui/src/locale';
import CollapseTransition from 'element-ui/src/transitions/collapse-transition';

const components = [
  Dialog,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Tooltip,
  Tabs,
  TabPane,
  Row,
  Col,
  Tag,
  Icon,
  Spinner,
  Badge,
  Card,
  Scrollbar,
  Collapse,
  CollapseItem,
  Link,
  Divider,
  Backtop,
  Popover,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(Loading.directive);

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.13.0',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  Dialog,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Tooltip,
  Tabs,
  TabPane,
  Row,
  Col,
  Tag,
  Icon,
  Spinner,
  Message,
  Badge,
  Card,
  Scrollbar,
  Collapse,
  CollapseItem,
  Link,
  Divider,
  Backtop,
  Popover
};
